import {drizzle} from 'drizzle-orm/postgres-js';  // This is the drizzle-orm package
import {postgres} from 'postgres';  // This is the postgres package
import * as dotenv from 'dotenv';  // This is the dotenv package
import * as schema from '../../../migrations/schema.ts';  // This is the schema file generated by drizzle
import { migrate } from 'drizzle-orm/postgres-js/migrator';
dotenv.config({ path: '.env' });    // Load the .env file

if (!process.env.DATABASE_URL) {  // Check if the DATABASE_URL is set
    console.log('DATABASE_URL is not set');   // Log a message to the console
}

const client = postgres(process.env.DATABASE_URL as string, max: 1 );   // This is the postgres client
const db = drizzle(client, schema); // This is the default export
const migrateDb = async () => {
    try {
        console.log('🟠 Migrating database...');  // Log a message to the console
        await migrate(db, {migrationsFolder: './migrations'});  // Migrate the database
        console.log('🟢 Successfully Migrated'); 
    } catch (error) {
        console.log('🔴 Error Migrating client'); 
    }
   
} // This is an async function
migrateDb();  // Call the function
export default db;  // This is the default export
